name: gbfs_compare
channels:
  - conda-forge
  - defaults
dependencies:
  - _openmp_mutex=4.5
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2025.8.3
  - contourpy=1.3.0
  - cycler=0.12.1
  - double-conversion=3.3.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.59.1
  - freetype=2.14.1
  - graphite2=1.3.14
  - h5py=3.14.0
  - harfbuzz=11.4.5
  - hdf5=1.14.6
  - icu=75.1
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - joblib=1.5.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libaec=1.1.4
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libclang13=21.1.7
  - libcurl=8.17.0
  - libdeflate=1.25
  - libexpat=2.7.3
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libglib=2.84.3
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libpng=1.6.53
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libxslt=1.1.43
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - matplotlib=3.9.4
  - matplotlib-base=3.9.4
  - mkl=2025.3.0
  - munkres=1.1.4
  - networkx=3.2.1
  - numpy=1.26.4
  - openjpeg=2.5.4
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.3.1
  - pcre2=10.45
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - pthread-stubs=0.4
  - pyparsing=3.2.3
  - pyside6=6.9.1
  - python=3.9.23
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.9
  - pytz=2025.2
  - qhull=2020.2
  - qt6-main=6.9.1
  - scikit-learn=1.6.1
  - scipy=1.13.1
  - setuptools=80.9.0
  - six=1.17.0
  - tbb=2022.3.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tornado=6.5.2
  - tzdata=2025c
  - ucrt=10.0.26100.0
  - unicodedata2=16.0.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zipp=3.23.0
  - zstd=1.5.7
  - pip:
      - imbalanced-learn==0.12.4
      - imblearn==0.0
      - itmo-fs==0.3.3
      - pyifs==0.0.3
      - qpsolvers==4.8.2
